2016-10-26 11:10:17,727 - teradata.udaexec - INFO - Initializing UdaExec...
2016-10-26 11:10:17,727 - teradata.udaexec - INFO - Reading config files: ['/etc/udaexec.ini: Not Found', '/Users/vro173/udaexec.ini: Not Found', '/Users/vro173/Documents/Python_programs/udaexec.ini: Not Found']
2016-10-26 11:10:17,727 - teradata.udaexec - INFO - Found run number file: "/Users/vro173/Documents/Python_programs/.runNumber"
2016-10-26 11:10:17,727 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-10-26 11:10:17,728 - teradata.udaexec - INFO - Removed 0 log files.
2016-10-26 11:10:17,773 - teradata.udaexec - INFO - Checkpoint file not found: /Users/vro173/Documents/Python_programs/HelloWorld.checkpoint
2016-10-26 11:10:17,774 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-10-26 11:10:17,774 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: HelloWorld
 *          Version: 1.0
 *       Run Number: 20161026111017-27
 *             Host: acbc32a00557
 *         Platform: Darwin-15.6.0-x86_64-i386-64bit
 *          OS User: vro173
 *   Python Version: 3.5.2
 *  Python Compiler: GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)
 *     Python Build: ('default', 'Jul  2 2016 17:52:12')
 *  UdaExec Version: 15.10.0.20
 *     Program Name: classify_tables.py
 *      Working Dir: /Users/vro173/Documents/Python_programs
 *          Log Dir: /Users/vro173/Documents/Python_programs/logs
 *         Log File: /Users/vro173/Documents/Python_programs/logs/HelloWorld.20161026111017-27.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/Users/vro173/udaexec.ini: Not Found', '/Users/vro173/Documents/Python_programs/udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=HelloWorld;Version=1.0;JobID=20161026111017-27;ClientUser=vro173;Production=False;udaAppLogFile=/Users/vro173/Documents/Python_programs/logs/HelloWorld.20161026111017-27.log;UtilityName=PyTd;UtilityVersion=15.10.0.20
********************************************************************************/
2016-10-26 11:10:17,781 - teradata.udaexec - INFO - Creating connection: {'method': 'odbc', 'password': 'XXXXXX', 'username': 'vro173', 'system': 'oneview'}
2016-10-26 11:10:17,782 - teradata.tdodbc - INFO - Loading ODBC Library: libiodbc.dylib
2016-10-26 11:10:17,787 - teradata.tdodbc - INFO - Available drivers: Amazon Redshift, MapR Drill ODBC Driver, MySQL ODBC 5.3 ANSI Driver, MySQL ODBC 5.3 Unicode Driver, PostgreSQL Unicode, Simba SQL Server ODBC Driver, Teradata
2016-10-26 11:10:24,567 - teradata.udaexec - INFO - Connection successful. Duration: 6.785 seconds. Details: {'method': 'odbc', 'password': 'XXXXXX', 'username': 'vro173', 'system': 'oneview'}
2016-10-26 11:10:32,282 - teradata.udaexec - INFO - Query Successful. Duration: 5.157 seconds, Rows: 12, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND__122006';
2016-10-26 11:10:37,908 - teradata.udaexec - INFO - Query Successful. Duration: 5.621 seconds, Rows: 4, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_41789_042009';
2016-10-26 11:10:40,978 - teradata.udaexec - INFO - Query Successful. Duration: 3.063 seconds, Rows: 3, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_41789_CCB_042009';
2016-10-26 11:10:43,744 - teradata.udaexec - INFO - Query Successful. Duration: 2.762 seconds, Rows: 21, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_CAT1_AFFILIATE_122006';
2016-10-26 11:10:45,601 - teradata.udaexec - INFO - Query Successful. Duration: 1.852 seconds, Rows: 143, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_CAT1_APPLICATION_122006';
2016-10-26 11:10:47,123 - teradata.udaexec - INFO - Query Successful. Duration: 1.513 seconds, Rows: 4, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_CAT1_APR_TRNS_122006';
2016-10-26 11:10:56,545 - teradata.udaexec - ERROR - Uncaught exception
Traceback (most recent call last):
  File "classify_tables.py", line 25, in <module>
    c.execute("SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='{0}' AND TABLENAME = '{1}';".format(row[0], row[1]))
  File "/Users/vro173/anaconda/lib/python3.5/site-packages/teradata/udaexec.py", line 745, in execute
    self._execute(self.cursor.execute, query, params, **kwargs)
  File "/Users/vro173/anaconda/lib/python3.5/site-packages/teradata/udaexec.py", line 790, in _execute
    func(query, params, **kwargs)
  File "/Users/vro173/anaconda/lib/python3.5/site-packages/teradata/tdodbc.py", line 591, in execute
    self.hStmt, _inputStr(_convertLineFeeds(query)), SQL_NTS)
KeyboardInterrupt
2016-10-26 11:10:56,548 - teradata.tdodbc - WARNING - 1 open connections found on exit, attempting to close...
2016-10-26 11:10:58,284 - teradata.udaexec - INFO - UdaExec exiting.
